// 口袋句庫 Pocketbrief：英文、日文翻譯表（由繁體中文原文查詢）
// Copyright (c) 2026 無名小律師（楊朝淵律師）. Licensed under the MIT License; see the LICENSE file.
// 每三個一組：繁體中文（須與程式裡的原文一字不差）、English、日本語。
enum LangTable {
    static let entries: [String] = [
        "{0} 已啟動", "{0} is running", "{0} を起動しました",
        "按 {0} 叫出範本清單", "Press {0} to show the template list", "{0} でテンプレート一覧を表示",
        "；反白文字後按 {0} 快速新增", "; select text and press {0} to quick-add", "。文字を選択して {0} でクイック追加",
        "快速鍵被占用", "Hotkey already in use", "ショートカットキーが使用中です",
        "{0} 已被其他程式使用，請在「設定」改用別的組合。", "{0} is already used by another program. Please choose a different combination in Settings.", "{0} は他のプログラムで使われています。「設定」で別の組み合わせにしてください。",
        "快速鍵設定有誤", "Invalid hotkey", "ショートカットキーの設定エラー",
        "請在「設定」重新指定叫出清單的快速鍵。", "Please set the list hotkey again in Settings.", "「設定」で一覧のショートカットキーを設定し直してください。",
        "快速鍵無法啟用", "Hotkey unavailable", "ショートカットキーを有効にできません",
        "快速新增的快速鍵無法使用", "Quick-add hotkey unavailable", "クイック追加のショートカットキーが使えません",
        "{0} 設定有誤或已被其他程式使用，請在「設定」改用別的組合。", "{0} is invalid or used by another program. Please choose a different combination in Settings.", "{0} は設定が正しくないか、他のプログラムで使われています。「設定」で別の組み合わせにしてください。",
        "快速新增沒有執行", "Quick-add was not run", "クイック追加を実行しませんでした",
        "已新增範本", "Template added", "テンプレートを追加しました",
        "代碼 {0}：", "Code {0}: ", "コード {0}：",
        "設定檔暫時無法寫入（可能正在同步），新設定這次有效，但沒有存檔；請稍後再到「設定」按一次確定。", "The settings file cannot be written right now (it may be syncing). The new settings apply for now but were not saved; please click OK in Settings again later.", "設定ファイルに書き込めません（同期中の可能性があります）。新しい設定は今回だけ有効で、保存されていません。しばらくしてから「設定」でもう一度 OK を押してください。",
        "版本 {0}", "Version {0}", "バージョン {0}",
        "本程式以 MIT 授權開源，可自由使用、修改與散布。", "Open source under the MIT License: free to use, modify and distribute.", "MIT ライセンスのオープンソースです。自由に使用・改変・再配布できます。",
        "句庫管理…", "Phrase Library…", "フレーズ管理…",
        "設定…", "Settings…", "設定…",
        "關於…", "About…", "バージョン情報…",
        "結束", "Exit", "終了",
        "關於 {0}", "About {0}", "{0} について",
        "新增範本", "New template", "新しいテンプレート",
        "儲存", "Save", "保存",
        "匯入 CSV…", "Import CSV…", "CSV を読み込む…",
        "匯出 CSV…", "Export CSV…", "CSV に書き出す…",
        "搜尋", "Search", "検索",
        "{0}－句庫管理（叫出清單的快速鍵：{1}）", "{0} – Phrase Library (list hotkey: {1})", "{0} － フレーズ管理（一覧のショートカット：{1}）",
        "＋ 新增範本", "+ New template", "＋ 新規テンプレート",
        "刪除", "Delete", "削除",
        "名稱、代碼或內容", "Name, code or content", "名前・コード・内容",
        "內容字級", "Text size", "文字サイズ",
        "範本清單與編輯區的文字大小（不影響視窗與按鈕的大小）", "Text size of the template list and editor (does not change the size of windows or buttons)", "一覧と編集欄の文字サイズ（ウィンドウやボタンの大きさは変わりません）",
        "代碼", "Code", "コード",
        "名稱", "Name", "名前",
        "內容", "Content", "内容",
        "復原", "Revert", "元に戻す",
        "英文字母、數字或符號，最多 20 碼（不分大小寫）。叫出清單後打這組代碼就會直接輸出。", "Letters, digits or symbols, up to 20 characters (case-insensitive). Type this code in the list to insert the template instantly.", "英字・数字・記号、最大 20 文字（大文字小文字を区別しません）。一覧を呼び出してこのコードを打つと、すぐに入力されます。",
        "共 {0} 筆", "{0} templates", "全 {0} 件",
        "符合 {0}／{1} 筆", "{0} of {1} match", "該当 {0}／{1} 件",
        "編輯範本", "Edit template", "テンプレートを編集",
        "在左側點選一筆範本即可編輯，或按「＋ 新增範本」。", "Select a template on the left to edit it, or click \"+ New template\".", "左の一覧からテンプレートを選ぶと編集できます。「＋ 新規テンプレート」で追加もできます。",
        "已選取 {0} 筆範本（可按「刪除」一次刪除）", "{0} templates selected (click \"Delete\" to delete them all)", "{0} 件のテンプレートを選択中（「削除」でまとめて削除できます）",
        "字數：{0}", "Characters: {0}", "文字数：{0}",
        "已儲存。", "Saved.", "保存しました。",
        "新範本", "New template", "新しいテンプレート",
        "「{0}」有尚未儲存的修改，要儲存嗎？", "\"{0}\" has unsaved changes. Save them?", "「{0}」に未保存の変更があります。保存しますか？",
        "取消", "Cancel", "キャンセル",
        "確定要刪除「{0}」嗎？", "Delete \"{0}\"?", "「{0}」を削除しますか？",
        "確定要刪除選取的 {0} 筆範本嗎？", "Delete the {0} selected templates?", "選択した {0} 件のテンプレートを削除しますか？",
        "已匯出 {0} 筆範本：\n{1}", "Exported {0} templates:\n{1}", "{0} 件のテンプレートを書き出しました：\n{1}",
        "提醒：這個檔案可以用 Excel 開來看，但不建議用 Excel 修改後另存——Excel 會把代碼開頭的 0 去掉（01 變成 1）、把 1-2 當成日期、把 = 或 + 開頭的內容當成公式。要修改範本，請在「句庫管理」裡改。", "Note: you can open this file in Excel to view it, but avoid editing and re-saving it there. Excel drops leading zeros from codes (01 becomes 1), turns 1-2 into a date, and treats content starting with = or + as a formula. Please edit templates in the Phrase Library instead.", "ご注意：このファイルは Excel で開いて見ることはできますが、Excel で編集して保存し直すのはお勧めしません。Excel はコード先頭の 0 を消し（01 が 1 になる）、1-2 を日付に変え、= や + で始まる内容を数式として扱います。テンプレートの修正はフレーズ管理で行ってください。",
        "匯出失敗：", "Export failed: ", "書き出しに失敗しました：",
        "讀取失敗：", "Could not read the file: ", "読み込みに失敗しました：",
        "為避免覆蓋掉資料，這次不匯入。", "To avoid overwriting your data, nothing was imported.", "データの上書きを避けるため、今回は読み込みません。",
        "在「{0}」裡沒有讀到任何範本。", "No templates were found in \"{0}\".", "「{0}」からテンプレートが見つかりませんでした。",
        "從「{0}」讀到 {1} 筆，全部都已經在清單裡了，不需要匯入。", "Read {1} templates from \"{0}\"; all of them are already in your list, so there is nothing to import.", "「{0}」から {1} 件を読み込みましたが、すべて一覧にあるため読み込む必要はありません。",
        "‧新範本 {0} 筆", "• New templates: {0}", "・新しいテンプレート {0} 件",
        "‧已經存在、略過 {0} 筆", "• Already in your list, skipped: {0}", "・すでに存在するためスキップ {0} 件",
        "‧有 {0} 筆的代碼含空白、中文或超過 20 碼，無法用來叫出，已改為無代碼（內容照常匯入）", "• {0} codes contain spaces, CJK characters or more than 20 characters and cannot be typed; they were cleared (the content is still imported)", "・{0} 件のコードにスペース・全角文字が含まれるか 20 文字を超えていて使えないため、コードなしにしました（内容はそのまま読み込みます）",
        "‧代碼跟現有範本相同、但內容不同 {0} 筆（例如代碼 {1}）", "• Same code as an existing template but different content: {0} (e.g. code {1})", "・既存のテンプレートとコードが同じで内容が異なるもの {0} 件（例：コード {1}）",
        "從「{0}」讀到 {1} 筆：", "Read {1} templates from \"{0}\":", "「{0}」から {1} 件を読み込みました：",
        "確定要匯入嗎？", "Import them?", "読み込みますか？",
        "匯入完成，目前共有 {0} 筆範本。", "Import complete. You now have {0} templates.", "読み込みが完了しました。現在 {0} 件のテンプレートがあります。",
        "請打代碼", "Type a code", "コードを入力",
        "代碼：{0}", "Code: {0}", "コード：{0}",
        "（還沒有範本，按 F2 開啟句庫管理新增）", "(No templates yet. Press F2 to open the Phrase Library and add one.)", "（テンプレートがありません。F2 でフレーズ管理を開いて追加してください）",
        "（沒有符合的範本）", "(No matching templates)", "（該当するテンプレートがありません）",
        "快速新增範本", "Quick-add template", "テンプレートをクイック追加",
        "確認", "OK", "確定",
        "護眼配色：低對比、少藍光，適合長時間閱讀。", "Eye-care colors: low contrast and less blue light, easy on the eyes for long reading.", "目にやさしい配色：コントラストとブルーライトを抑え、長時間の閲覧に向いています。",
        "法院公鑒", "Closing", "結び",
        "此致 ⏎ 臺灣臺北地方法院　公鑒", "Respectfully submitted ⏎ To the Honorable Court", "以上 ⏎ 東京地方裁判所 御中",
        "審閱檢查", "Review", "レビュー",
        "幫我用 /legal-reviewer審閱、檢查一下", "Please review and check this with /legal-reviewer", "/legal-reviewer でレビューとチェックをお願いします",
        "聯絡資訊", "Contact", "連絡先",
        "電子郵件：name@example.com", "Email: name@example.com", "メール：name@example.com",
        "此致\n臺灣臺北地方法院　公鑒", "Respectfully submitted,\nTo the Honorable Court", "以上\n東京地方裁判所 御中",
        "打的代碼只對應到一筆時，不必按 Enter 就直接輸出", "Insert immediately (without Enter) when the typed code matches only one template", "入力したコードに一致するテンプレートが 1 件だけなら、Enter なしですぐ入力する",
        "輸出後把剪貼簿還原成原本的內容", "Restore the original clipboard content after inserting", "入力後、クリップボードを元の内容に戻す",
        "{0} 設定", "{0} Settings", "{0} の設定",
        "快速鍵與行為", "Hotkeys & Behavior", "ショートカットと動作",
        "清單外觀", "List Appearance", "一覧の外観",
        "確定", "OK", "OK",
        "跟隨系統", "System", "システムに従う",
        "淺色", "Light", "ライト",
        "深色", "Dark", "ダーク",
        "叫出範本清單", "Show template list", "テンプレート一覧を表示",
        "句庫內容字體大小", "Phrase text size", "フレーズの文字サイズ",
        "更改語言後，程式會自動重新啟動。", "The program restarts automatically after you change the language.", "言語を変更すると、プログラムは自動的に再起動します。",
        "外觀模式", "Appearance", "外観モード",
        "配色主題（點一下套用）", "Color themes (click to apply)", "配色テーマ（クリックで適用）",
        "筆", "rows", "件",
        "底色", "Background", "背景色",
        "文字顏色", "Text", "文字色",
        "代碼顏色", "Code", "コードの色",
        "選取列底色", "Selected row", "選択行の背景",
        "選取列文字", "Selected text", "選択行の文字",
        "標題列底色", "Title bar", "タイトルバーの背景",
        "標題列文字", "Title text", "タイトルバーの文字",
        "恢復預設外觀", "Reset to default", "既定の外観に戻す",
        "字型", "Font", "フォント",
        "字體大小", "Font size", "文字サイズ",
        "清單寬度", "List width", "一覧の幅",
        "一次顯示", "Show", "表示件数",
        "預覽", "Preview", "プレビュー",
        "（這台電腦沒有安裝）", " (not installed on this computer)", "（このパソコンには未インストール）",
        "叫出清單的快速鍵看不懂，請重新設定。", "The hotkey for showing the list is not valid. Please set it again.", "一覧を呼び出すショートカットキーが正しくありません。設定し直してください。",
        "快速新增的快速鍵看不懂，請重新設定。", "The quick-add hotkey is not valid. Please set it again.", "クイック追加のショートカットキーが正しくありません。設定し直してください。",
        "兩組快速鍵不能相同。", "The two hotkeys cannot be the same.", "2 つのショートカットキーを同じにはできません。",
        "找不到範本檔（可能正在同步），暫時沿用上次讀到的內容。", "The template file cannot be found (it may be syncing). Using the last loaded content for now.", "テンプレートファイルが見つかりません（同期中の可能性があります）。前回読み込んだ内容をそのまま使います。",
        "範本檔一直在變動（可能正在同步），暫時沿用上次讀到的內容。", "The template file keeps changing (it may be syncing). Using the last loaded content for now.", "テンプレートファイルが変更され続けています（同期中の可能性があります）。前回読み込んだ内容をそのまま使います。",
        "讀不到範本檔：", "Cannot read the template file: ", "テンプレートファイルを読み込めません：",
        "範本檔是空的（可能正在同步），暫時沿用上次讀到的內容。", "The template file is empty (it may be syncing). Using the last loaded content for now.", "テンプレートファイルが空です（同期中の可能性があります）。前回読み込んだ内容をそのまま使います。",
        "範本檔不完整（可能正在同步），暫時沿用上次讀到的內容。", "The template file is incomplete (it may be syncing). Using the last loaded content for now.", "テンプレートファイルが不完全です（同期中の可能性があります）。前回読み込んだ内容をそのまま使います。",
        "範本檔格式不正確（缺少欄位名稱那一列），暫時沿用上次讀到的內容。", "The template file has an invalid format (the header row is missing). Using the last loaded content for now.", "テンプレートファイルの形式が正しくありません（見出し行がありません）。前回読み込んだ内容をそのまま使います。",
        "為避免覆蓋掉資料，這次的修改沒有存檔。", "To avoid overwriting your data, this change was not saved.", "データの上書きを避けるため、今回の変更は保存されませんでした。",
        "存檔失敗：", "Save failed: ", "保存に失敗しました：",
        "範本檔一直在變動（可能正在同步），這次的修改沒有存檔，請稍後再試。", "The template file keeps changing (it may be syncing). This change was not saved; please try again later.", "テンプレートファイルが変更され続けています（同期中の可能性があります）。今回の変更は保存されませんでした。しばらくしてからもう一度お試しください。",
        "你剛輸入的內容已先複製到剪貼簿，可以稍後再貼回去。", "What you just typed has been copied to the clipboard so you can paste it back later.", "入力した内容はクリップボードにコピーしてあります。後で貼り付け直せます。",
        "內容不能是空白。", "The content cannot be empty.", "内容を空欄にはできません。",
        "代碼只能用英文字母、數字或半形符號，\n不能有空白、中文或 ` 鍵。", "A code may only contain letters, digits or half-width symbols,\nwith no spaces, CJK characters or the ` key.", "コードに使えるのは英字・数字・半角記号だけです。\nスペース、全角文字、` キーは使えません。",
        "代碼「{0}」已經被「{1}」使用了。\n\n代碼重複的話，打這組代碼時清單會停住，讓你用方向鍵和 Enter 選。\n仍要儲存嗎？", "The code \"{0}\" is already used by \"{1}\".\n\nWith a duplicate code, the list will pause when you type it and let you choose with the arrow keys and Enter.\nSave anyway?", "コード「{0}」はすでに「{1}」で使われています。\n\nコードが重複していると、入力時に一覧が止まり、矢印キーと Enter で選ぶことになります。\nそれでも保存しますか？",
        "經典藍", "Classic Blue", "クラシック",
        "豆沙綠", "Soft Green", "やさしい緑",
        "暖米紙", "Sepia", "セピア",
        "森林綠", "Forest", "フォレスト",
        "摩卡棕", "Mocha", "モカ",
        "朱紅", "Vermilion", "朱色",
        "紫藤", "Wisteria", "藤色",
        "Solarized", "Solarized", "Solarized",
        "高對比", "High Contrast", "高コントラスト",
        "。\n點選單列的圖示可管理範本。", ".\nClick the menu bar icon to manage your templates.", "。\nメニューバーのアイコンからテンプレートを管理できます。",
        "{0}已經在執行了（請看選單列的圖示）。", "{0} is already running (look for its icon in the menu bar).", "{0} はすでに実行中です（メニューバーのアイコンを確認してください）。",
        "{0} 需要「輸入監控」權限。請到「系統設定」→「隱私權與安全性」→「輸入監控」打開 Pocketbrief，再重新啟動程式。", "{0} needs the Input Monitoring permission. Go to System Settings → Privacy & Security → Input Monitoring, turn on Pocketbrief, then restart the app.", "{0} には「入力監視」の許可が必要です。「システム設定」→「プライバシーとセキュリティ」→「入力監視」で Pocketbrief をオンにしてから、アプリを再起動してください。",
        "請先放開 ⌘、⇧ 等按鍵，再按一次 {0}。", "Release ⌘, ⇧ and other modifier keys first, then press {0} again.", "⌘ や ⇧ などのキーを離してから、もう一度 {0} を押してください。",
        "無法設定登入時自動啟動：", "Couldn't set up launching at login: ", "ログイン時の自動起動を設定できませんでした：",
        "開啟句庫資料夾", "Open Library Folder", "ライブラリのフォルダを開く",
        "隱藏 {0}", "Hide {0}", "{0} を非表示",
        "結束 {0}", "Quit {0}", "{0} を終了",
        "檔案", "File", "ファイル",
        "關閉視窗", "Close Window", "ウインドウを閉じる",
        "編輯", "Edit", "編集",
        "還原", "Undo", "取り消す",
        "重做", "Redo", "やり直す",
        "剪下", "Cut", "カット",
        "拷貝", "Copy", "コピー",
        "貼上", "Paste", "ペースト",
        "全選", "Select All", "すべてを選択",
        "視窗", "Window", "ウインドウ",
        "縮到最小", "Minimize", "しまう",
        "口袋句庫把範本（範本.csv）存在一個資料夾裡。把這個資料夾放在雲端硬碟，就能和其他電腦（包括 Windows 版）共用同一個句庫。", "Pocketbrief keeps your templates (範本.csv) in a folder. Put that folder in a cloud drive to share one library with your other computers, including the Windows version.", "Pocketbrief はテンプレート（範本.csv）をひとつのフォルダに保存します。このフォルダをクラウドドライブに置けば、Windows 版を含むほかのパソコンと同じライブラリを共有できます。",
        "在 Google 雲端硬碟找到現有的句庫：\n{0}", "Found an existing library in Google Drive:\n{0}", "Google ドライブに既存のライブラリが見つかりました：\n{0}",
        "使用這個資料夾", "Use This Folder", "このフォルダを使う",
        "選擇資料夾…", "Choose Folder…", "フォルダを選択…",
        "使用預設位置（文件）", "Use Default (Documents)", "標準の場所を使う（書類）",
        "選擇句庫資料夾", "Choose a Library Folder", "ライブラリのフォルダを選択",
        "選擇", "Choose", "選択",
        "選擇句庫資料夾（範本.csv 所在的資料夾）", "Choose the library folder (the folder that contains 範本.csv)", "ライブラリのフォルダ（範本.csv があるフォルダ）を選択してください",
        "空白鍵", "Space", "スペース",
        "新增一筆範本（⌘N）", "Add a template (⌘N)", "テンプレートを追加（⌘N）",
        "刪除選取的範本（⌫）", "Delete the selected templates (⌫)", "選択したテンプレートを削除（⌫）",
        "　（尚未儲存，⌘S 儲存）", "  (unsaved — press ⌘S to save)", "　（未保存。⌘S で保存）",
        "不儲存", "Don't Save", "保存しない",
        "請先在左側點選要刪除的範本（按住 ⌘ 或 ⇧ 可以多選）。", "Select the templates to delete on the left first (hold ⌘ or ⇧ to select several).", "削除するテンプレートを左側で選択してください（⌘ または ⇧ を押しながらクリックすると複数選択できます）。",
        "代碼相同的要怎麼處理？「取代」會用匯入的內容取代現有那筆；「兩筆都保留」的話，打這組代碼時清單會停住讓你選。", "What should happen to templates with the same code? \"Replace\" overwrites the existing one with the imported content; \"Keep Both\" keeps both, and the list will pause on that code so you can choose.", "コードが同じものはどうしますか？「置き換える」は既存のものを読み込んだ内容で置き換えます。「両方残す」と、そのコードを入力したときに一覧が止まって選べるようになります。",
        "取代", "Replace", "置き換える",
        "兩筆都保留", "Keep Both", "両方残す",
        "匯入", "Import", "読み込む",
        "打代碼跳選　↑↓ 移動　↩ 輸出　⌫ 刪代碼　esc 取消　F2 句庫管理", "Type a code to jump   ↑↓ Move   ↩ Insert   ⌫ Delete code   esc Cancel   F2 Phrase Library", "コードで移動　↑↓ 移動　↩ 入力　⌫ コード削除　esc キャンセル　F2 フレーズ管理",
        "　（⌘↩ 確認）", "  (⌘↩ to confirm)", "　（⌘↩ で確定）",
        "口袋句庫 Pocketbrief Mac 版設定檔（請在選單列圖示 →「設定…」修改，不必手動編輯本檔）", "Pocketbrief for Mac settings (change them from the menu bar icon → Settings…; no need to edit this file by hand)", "Pocketbrief Mac 版の設定ファイル（メニューバーのアイコン →「設定…」で変更できます。このファイルを直接編集する必要はありません）",
        "範本清單外觀（顏色空白＝跟隨系統配色）", "List appearance (empty color = follow the system)", "一覧の外観（色が空欄＝システムの配色に従う）",
        "` + …（請再按一個鍵）", "` + … (press another key)", "` + …（もう一つキーを押してください）",
        "請按下組合鍵", "Press a key combination", "キーの組み合わせを押してください",
        "（未設定）", "(not set)", "（未設定）",
        "登入時自動啟動（每台 Mac 各自設定）", "Launch at login (set separately on each Mac)", "ログイン時に自動で起動する（Mac ごとに設定）",
        "自動（依系統語言）", "Automatic (follow system)", "自動（システムの言語に従う）",
        "變更…", "Change…", "変更…",
        "開啟系統設定", "Open System Settings", "システム設定を開く",
        "點一下格子，直接按下想用的組合鍵（例如 ⌃`、⌥`、F9），\n或按住 ` 再按一個鍵（例如 `+1）。單獨一個鍵（F1～F12 除外）不能當快速鍵，避免打字時誤觸。", "Click the box and press the key combination you want (e.g. ⌃`, ⌥`, F9),\nor hold ` and press another key (e.g. `+1). A single key on its own (except F1–F12) can't be used, so it won't trigger while typing.", "欄をクリックして、使いたいキーの組み合わせを押してください（例：⌃`、⌥`、F9）。\n` を押したまま別のキーを押す組み合わせ（例：`+1）も使えます。入力中の誤操作を防ぐため、単独のキー（F1～F12 を除く）は使えません。",
        "在任何地方先反白一段文字，再按這組鍵，就會開啟「新增範本」並自動帶入反白的內容。\n點格子後按 ⌫ 可清除（停用此功能）。", "Select some text anywhere, then press this combination to open \"Add template\" with the selected text filled in.\nClick the box and press ⌫ to clear it (turn this off).", "どこかでテキストを選択してからこのキーを押すと、選択した内容が入った状態で「テンプレートを追加」が開きます。\n欄をクリックして ⌫ を押すとクリア（この機能をオフ）できます。",
        "句庫管理裡範本清單與編輯區的文字大小。叫出的範本清單則到「清單外觀」分頁調整。", "Text size of the template list and editor in the Phrase Library. For the pop-up list, use the List Appearance tab.", "フレーズ管理のテンプレート一覧と編集欄の文字サイズです。呼び出す一覧は「一覧の外観」タブで調整します。",
        "深色模式會套用到句庫管理、設定等視窗。叫出的範本清單有自己的配色，請到「清單外觀」分頁選擇（例如「深色」主題）。", "Dark mode applies to the Phrase Library, Settings and other windows. The pop-up list has its own colors; choose them on the List Appearance tab (e.g. the Dark theme).", "ダークモードはフレーズ管理や設定などのウインドウに適用されます。呼び出す一覧には独自の配色があるので、「一覧の外観」タブで選んでください（例：「ダーク」テーマ）。",
        "句庫資料夾", "Library folder", "ライブラリのフォルダ",
        "範本.csv 與設定都存在這個資料夾。想和 Windows 版或其他 Mac 共用句庫，請選雲端硬碟裡同一個資料夾。", "範本.csv and your settings are stored in this folder. To share the library with the Windows version or other Macs, choose the same folder in your cloud drive.", "範本.csv と設定はこのフォルダに保存されます。Windows 版やほかの Mac とライブラリを共有するには、クラウドドライブ内の同じフォルダを選んでください。",
        "輔助使用", "Accessibility", "アクセシビリティ",
        "貼上範本、讀取游標位置、快速新增都需要這個權限。", "Needed to paste templates, find the cursor position, and quick-add.", "テンプレートの貼り付け、カーソル位置の取得、クイック追加に必要です。",
        "輸入監控", "Input Monitoring", "入力監視",
        "只有快速鍵設成「` + 某個鍵」時才需要。", "Only needed when a hotkey is set to \"` + a key\".", "ショートカットキーを「` + キー」に設定した場合だけ必要です。",
        "✅ 已開啟", "✅ On", "✅ オン",
        "⚠️ 尚未開啟", "⚠️ Not turned on", "⚠️ まだオフです",
        "需要「輔助使用」權限", "Accessibility permission needed", "「アクセシビリティ」の許可が必要です",
        "口袋句庫要把範本貼到游標所在的位置，需要 macOS 的「輔助使用」權限。\n\n請到「系統設定」→「隱私權與安全性」→「輔助使用」，打開「Pocketbrief」。\n\n如果清單裡已經有 Pocketbrief 卻仍無法使用（例如剛更新過程式），請先用「－」把它移除，再重新加入。", "To paste templates where your cursor is, Pocketbrief needs the macOS Accessibility permission.\n\nGo to System Settings → Privacy & Security → Accessibility and turn on Pocketbrief.\n\nIf Pocketbrief is already in the list but still doesn't work (for example, right after an update), remove it with \"–\" and add it again.", "カーソルの位置にテンプレートを貼り付けるには、macOS の「アクセシビリティ」の許可が必要です。\n\n「システム設定」→「プライバシーとセキュリティ」→「アクセシビリティ」で Pocketbrief をオンにしてください。\n\nすでに一覧にあるのに動かない場合（アップデート直後など）は、「－」でいったん削除してから追加し直してください。",
        "稍後", "Later", "あとで",
        "已複製到剪貼簿", "Copied to the clipboard", "クリップボードにコピーしました",
        "請按 ⌘V 貼上。開啟「輔助使用」權限後就能自動貼上。", "Press ⌘V to paste. Turn on the Accessibility permission to paste automatically.", "⌘V で貼り付けてください。「アクセシビリティ」を許可すると自動で貼り付けられます。",
    ]
}
