// 口袋句庫 Pocketbrief：英文、日文翻譯表（每三個字串一組：繁體中文原文、English、日本語）
// Copyright (c) 2026 無名小律師（楊朝淵律師）. Licensed under the MIT License; see the LICENSE file.
// 新增介面文字時，把繁體中文原文（要和程式裡 L.T／L.F 的字串一字不差）連同兩種翻譯加在這裡；
// {0}、{1} 是插入值的位置，翻譯時要保留。
namespace Pocketbrief
{
    static partial class L
    {
        static readonly string[] LangTable =
        {
            // ── 設定檔註解 ──
            "口袋句庫 Pocketbrief 設定檔（請在系統匣圖示按右鍵 →「設定」修改，不必手動編輯本檔）",
            "Pocketbrief settings file (change these via right-click on the tray icon → Settings; no need to edit this file by hand)",
            "Pocketbrief 設定ファイル（タスクトレイのアイコンを右クリック →「設定」で変更できます。直接編集する必要はありません）",
            "範本清單外觀（顏色空白＝跟隨 Windows 系統配色）",
            "Template list appearance (an empty color = follow Windows system colors)",
            "テンプレート一覧の外観（色が空欄＝Windows のシステム配色に従う）",

            // ── 範本檔讀寫 ──
            "找不到範本檔（可能正在同步），暫時沿用上次讀到的內容。",
            "The template file cannot be found (it may be syncing). Using the last loaded content for now.",
            "テンプレートファイルが見つかりません（同期中の可能性があります）。前回読み込んだ内容をそのまま使います。",
            "範本檔是空的（可能正在同步），暫時沿用上次讀到的內容。",
            "The template file is empty (it may be syncing). Using the last loaded content for now.",
            "テンプレートファイルが空です（同期中の可能性があります）。前回読み込んだ内容をそのまま使います。",
            "範本檔不完整（可能正在同步），暫時沿用上次讀到的內容。",
            "The template file is incomplete (it may be syncing). Using the last loaded content for now.",
            "テンプレートファイルが不完全です（同期中の可能性があります）。前回読み込んだ内容をそのまま使います。",
            "範本檔格式不正確（缺少欄位名稱那一列），暫時沿用上次讀到的內容。",
            "The template file has an invalid format (the header row is missing). Using the last loaded content for now.",
            "テンプレートファイルの形式が正しくありません（見出し行がありません）。前回読み込んだ内容をそのまま使います。",
            "範本檔一直在變動（可能正在同步），暫時沿用上次讀到的內容。",
            "The template file keeps changing (it may be syncing). Using the last loaded content for now.",
            "テンプレートファイルが変更され続けています（同期中の可能性があります）。前回読み込んだ内容をそのまま使います。",
            "讀不到範本檔：",
            "Cannot read the template file: ",
            "テンプレートファイルを読み込めません：",
            "為避免覆蓋掉資料，這次的修改沒有存檔。",
            "To avoid overwriting your data, this change was not saved.",
            "データの上書きを避けるため、今回の変更は保存されませんでした。",
            "存檔失敗：",
            "Save failed: ",
            "保存に失敗しました：",
            "範本檔一直在變動（可能正在同步），這次的修改沒有存檔，請稍後再試。",
            "The template file keeps changing (it may be syncing). This change was not saved; please try again later.",
            "テンプレートファイルが変更され続けています（同期中の可能性があります）。今回の変更は保存されませんでした。しばらくしてからもう一度お試しください。",
            "你剛輸入的內容已先複製到剪貼簿，可以稍後再貼回去。",
            "What you just typed has been copied to the clipboard so you can paste it back later.",
            "入力した内容はクリップボードにコピーしてあります。後で貼り付け直せます。",
            "剪貼簿被其他程式占用，請再試一次。",
            "The clipboard is being used by another program. Please try again.",
            "クリップボードが他のプログラムに使用されています。もう一度お試しください。",

            // ── 叫出的範本清單 ──
            "打代碼跳選　↑↓ 移動　Enter 輸出　Backspace 刪代碼　Esc 取消　F2 句庫管理",
            "Type a code to jump   ↑↓ Move   Enter Insert   Backspace Delete code   Esc Cancel   F2 Phrase Library",
            "コード入力で選択　↑↓ 移動　Enter 入力　Backspace コード削除　Esc 取消　F2 フレーズ管理",
            "（還沒有範本，按 F2 開啟句庫管理新增）",
            "(No templates yet. Press F2 to open the Phrase Library and add one.)",
            "（テンプレートがありません。F2 でフレーズ管理を開いて追加してください）",
            "（沒有符合的範本）",
            "(No matching templates)",
            "（該当するテンプレートがありません）",
            "代碼：{0}",
            "Code: {0}",
            "コード：{0}",
            "請打代碼",
            "Type a code",
            "コードを入力",

            // ── 新增／修改 ──
            "名稱", "Name", "名前",
            "代碼", "Code", "コード",
            "英文字母、數字或符號，最多 20 碼（不分大小寫）。叫出清單後打這組代碼就會直接輸出。",
            "Letters, digits or symbols, up to 20 characters (case-insensitive). Type this code in the list to insert the template instantly.",
            "英字・数字・記号、最大 20 文字（大文字小文字を区別しません）。一覧を呼び出してこのコードを打つと、すぐに入力されます。",
            "內容", "Content", "内容",
            "確認", "OK", "確定",
            "取消", "Cancel", "キャンセル",
            "字數：{0}", "Characters: {0}", "文字数：{0}",
            "　（Ctrl+Enter 確認）", "   (Ctrl+Enter to confirm)", "　（Ctrl+Enter で確定）",
            "內容不能是空白。",
            "The content cannot be empty.",
            "内容を空欄にはできません。",
            "代碼只能用英文字母、數字或半形符號，\n不能有空白、中文或 ` 鍵。",
            "A code may only contain letters, digits or half-width symbols,\nwith no spaces, CJK characters or the ` key.",
            "コードに使えるのは英字・数字・半角記号だけです。\nスペース、全角文字、` キーは使えません。",
            "代碼「{0}」已經被「{1}」使用了。\n\n代碼重複的話，打這組代碼時清單會停住，讓你用方向鍵和 Enter 選。\n仍要儲存嗎？",
            "The code \"{0}\" is already used by \"{1}\".\n\nWith a duplicate code, the list will pause when you type it and let you choose with the arrow keys and Enter.\nSave anyway?",
            "コード「{0}」はすでに「{1}」で使われています。\n\nコードが重複していると、入力時に一覧が止まり、矢印キーと Enter で選ぶことになります。\nそれでも保存しますか？",

            // ── 設定視窗 ──
            "{0} 設定", "{0} Settings", "{0} の設定",
            "確定", "OK", "OK",
            "叫出清單的快速鍵看不懂，請重新設定。",
            "The hotkey for showing the list is not valid. Please set it again.",
            "一覧を呼び出すショートカットキーが正しくありません。設定し直してください。",
            "快速新增的快速鍵看不懂，請重新設定。",
            "The quick-add hotkey is not valid. Please set it again.",
            "クイック追加のショートカットキーが正しくありません。設定し直してください。",
            "兩組快速鍵不能相同。",
            "The two hotkeys cannot be the same.",
            "2 つのショートカットキーを同じにはできません。",
            "快速鍵與行為", "Hotkeys & Behavior", "ショートカットと動作",
            "叫出範本清單", "Show template list", "テンプレート一覧を表示",
            "點一下格子，直接按下想用的組合鍵（例如 Ctrl+`、Alt+`、F9），\n或按住 ` 再按一個鍵（例如 `+1）。單獨一個鍵（F1～F12 除外）不能當快速鍵，避免打字時誤觸。",
            "Click the box and press the key combination you want (e.g. Ctrl+`, Alt+`, F9),\nor hold ` and press another key (e.g. `+1). A single key on its own (except F1–F12) can't be used, so it won't trigger while typing.",
            "欄をクリックして、使いたいキーの組み合わせを押してください（例：Ctrl+`、Alt+`、F9）。\n` を押したまま別のキーを押す組み合わせ（例：`+1）も使えます。入力中の誤操作を防ぐため、単独のキー（F1～F12 を除く）は使えません。",
            "快速新增範本", "Quick-add template", "テンプレートをクイック追加",
            "在任何地方先反白一段文字，再按這組鍵，就會開啟「新增範本」並自動帶入反白的內容。\n在格子裡按 Backspace 可清除（停用此功能）。",
            "Select some text anywhere and press this key combination to open \"New template\" with the selected text filled in.\nPress Backspace in the box to clear it (turns this feature off).",
            "どこでも文字列を選択してからこのキーを押すと、選択した内容が入った「新しいテンプレート」が開きます。\n欄で Backspace を押すとクリアされます（この機能をオフにします）。",
            "視窗字體大小", "Window font size", "ウィンドウの文字サイズ",
            "各視窗的按鈕、選單、標籤等文字大小（預設 10.5）。放太大可能讓視窗超出螢幕。",
            "Text size of buttons, menus and labels in all windows (default 10.5). Too large may push windows off the screen.",
            "各ウィンドウのボタン・メニュー・ラベルなどの文字サイズ（既定値 10.5）。大きくしすぎるとウィンドウが画面からはみ出すことがあります。",
            "句庫內容字體大小", "Phrase text size", "フレーズの文字サイズ",
            "句庫管理裡範本清單與編輯區的文字大小，和上面的視窗字體分開調整，放大也不會讓視窗變大。\n在句庫管理的工具列上也可以直接調。叫出的範本清單則到「清單外觀」分頁調整。",
            "Text size of the template list and editor in the Phrase Library, set separately from the window font above; enlarging it does not enlarge the window.\nYou can also change it on the Phrase Library toolbar. For the pop-up list, use the \"List Appearance\" tab.",
            "フレーズ管理の一覧と編集欄の文字サイズです。上のウィンドウの文字サイズとは別に調整でき、大きくしてもウィンドウは大きくなりません。\nフレーズ管理のツールバーでも変更できます。ポップアップ一覧は「一覧の外観」タブで調整します。",
            "外觀模式", "Appearance", "外観モード",
            "跟隨 Windows", "Follow Windows", "Windows に従う",
            "淺色", "Light", "ライト",
            "深色模式會套用到句庫管理、設定等視窗。更改後，程式會自動重新啟動。\n叫出的範本清單有自己的配色，請到「清單外觀」分頁選擇（例如「深色」主題）。",
            "Dark mode applies to the Phrase Library, Settings and other windows. The program restarts automatically after you change it.\nThe pop-up list has its own colors; choose them on the \"List Appearance\" tab (e.g. the \"Dark\" theme).",
            "ダークモードはフレーズ管理や設定などのウィンドウに適用されます。変更すると、プログラムは自動的に再起動します。\nポップアップ一覧の配色は別に設定します。「一覧の外観」タブで選んでください（例：「ダーク」テーマ）。",
            "打的代碼只對應到一筆時，不必按 Enter 就直接輸出",
            "Insert immediately (without Enter) when the typed code matches only one template",
            "入力したコードに一致するテンプレートが 1 件だけなら、Enter なしですぐ入力する",
            "輸出後把剪貼簿還原成原本的內容",
            "Restore the original clipboard content after inserting",
            "入力後、クリップボードを元の内容に戻す",
            "開機時自動啟動（每台電腦各自設定）",
            "Start automatically when Windows starts (set separately on each computer)",
            "Windows 起動時に自動で開始する（パソコンごとに設定）",
            "自動（依 Windows 語言）", "Automatic (follow Windows)", "自動（Windows の言語に従う）",
            "更改語言後，程式會自動重新啟動。",
            "The program restarts automatically after you change the language.",
            "言語を変更すると、プログラムは自動的に再起動します。",
            "清單外觀", "List Appearance", "一覧の外観",
            "（這台電腦沒有安裝）", " (not installed on this computer)", "（このパソコンには未インストール）",
            "字型", "Font", "フォント",
            "字體大小", "Font size", "文字サイズ",
            "清單寬度", "List width", "一覧の幅",
            "一次顯示", "Show", "表示件数",
            "筆", "rows", "件",
            "底色", "Background", "背景色",
            "文字顏色", "Text", "文字色",
            "代碼顏色", "Code", "コードの色",
            "選取列底色", "Selected row", "選択行の背景",
            "選取列文字", "Selected text", "選択行の文字",
            "標題列底色", "Title bar", "タイトルバーの背景",
            "標題列文字", "Title text", "タイトルバーの文字",
            "恢復預設外觀", "Reset to default", "既定の外観に戻す",
            "預覽", "Preview", "プレビュー",
            "配色主題（點一下套用）", "Color themes (click to apply)", "配色テーマ（クリックで適用）",
            "跟隨系統", "System", "システムに従う",
            "法院公鑒", "Closing", "結び",
            "此致 ⏎ 臺灣臺北地方法院　公鑒", "Respectfully submitted ⏎ To the Honorable Court", "以上 ⏎ 東京地方裁判所 御中",
            "審閱檢查", "Review", "レビュー",
            "幫我用 /legal-reviewer審閱、檢查一下", "Please review and check this with /legal-reviewer", "/legal-reviewer でレビューとチェックをお願いします",
            "聯絡資訊", "Contact", "連絡先",
            "電子郵件：name@example.com", "Email: name@example.com", "メール：name@example.com",
            "此致\n臺灣臺北地方法院　公鑒", "Respectfully submitted,\nTo the Honorable Court", "以上\n東京地方裁判所 御中",

            // ── 範本管理視窗 ──
            "{0}－句庫管理（叫出清單的快速鍵：{1}）", "{0} – Phrase Library (list hotkey: {1})", "{0} － フレーズ管理（一覧のショートカット：{1}）",
            "＋ 新增範本", "+ New template", "＋ 新規テンプレート",
            "新增一筆範本（Ctrl+N）", "Add a new template (Ctrl+N)", "テンプレートを追加（Ctrl+N）",
            "刪除", "Delete", "削除",
            "刪除選取的範本（Delete）", "Delete the selected templates (Delete)", "選択したテンプレートを削除（Delete）",
            "匯入 CSV…", "Import CSV…", "CSV を読み込む…",
            "匯出 CSV…", "Export CSV…", "CSV に書き出す…",
            "搜尋", "Search", "検索",
            "名稱、代碼或內容", "Name, code or content", "名前・コード・内容",
            "設定…", "Settings…", "設定…",
            "內容字級", "Text size", "文字サイズ",
            "範本清單與編輯區的文字大小（不影響視窗與按鈕的大小）", "Text size of the template list and editor (does not change the size of windows or buttons)", "一覧と編集欄の文字サイズ（ウィンドウやボタンの大きさは変わりません）",
            "復原", "Revert", "元に戻す",
            "儲存", "Save", "保存",
            "共 {0} 筆", "{0} templates", "全 {0} 件",
            "符合 {0}／{1} 筆", "{0} of {1} match", "該当 {0}／{1} 件",
            "編輯範本", "Edit template", "テンプレートを編集",
            "在左側點選一筆範本即可編輯，或按「＋ 新增範本」。",
            "Select a template on the left to edit it, or click \"+ New template\".",
            "左の一覧からテンプレートを選ぶと編集できます。「＋ 新規テンプレート」で追加もできます。",
            "已選取 {0} 筆範本（可按「刪除」一次刪除）",
            "{0} templates selected (click \"Delete\" to delete them all)",
            "{0} 件のテンプレートを選択中（「削除」でまとめて削除できます）",
            "新增範本", "New template", "新しいテンプレート",
            "　（尚未儲存，Ctrl+S 儲存）", "   (unsaved – Ctrl+S to save)", "　（未保存。Ctrl+S で保存）",
            "已儲存。", "Saved.", "保存しました。",
            "新範本", "New template", "新しいテンプレート",
            "「{0}」有尚未儲存的修改，要儲存嗎？", "\"{0}\" has unsaved changes. Save them?", "「{0}」に未保存の変更があります。保存しますか？",
            "請先在左側點選要刪除的範本（按住 Ctrl 或 Shift 可以多選）。",
            "First select the templates to delete on the left (hold Ctrl or Shift to select several).",
            "削除するテンプレートを左の一覧で選んでください（Ctrl か Shift を押しながらで複数選択できます）。",
            "確定要刪除「{0}」嗎？", "Delete \"{0}\"?", "「{0}」を削除しますか？",
            "確定要刪除選取的 {0} 筆範本嗎？", "Delete the {0} selected templates?", "選択した {0} 件のテンプレートを削除しますか？",
            "CSV 檔案 (*.csv)|*.csv", "CSV files (*.csv)|*.csv", "CSV ファイル (*.csv)|*.csv",
            "已匯出 {0} 筆範本：\n{1}", "Exported {0} templates:\n{1}", "{0} 件のテンプレートを書き出しました：\n{1}",
            "提醒：這個檔案可以用 Excel 開來看，但不建議用 Excel 修改後另存——Excel 會把代碼開頭的 0 去掉（01 變成 1）、把 1-2 當成日期、把 = 或 + 開頭的內容當成公式。要修改範本，請在「句庫管理」裡改。",
            "Note: you can open this file in Excel to view it, but avoid editing and re-saving it there. Excel drops leading zeros from codes (01 becomes 1), turns 1-2 into a date, and treats content starting with = or + as a formula. Please edit templates in the Phrase Library instead.",
            "ご注意：このファイルは Excel で開いて見ることはできますが、Excel で編集して保存し直すのはお勧めしません。Excel はコード先頭の 0 を消し（01 が 1 になる）、1-2 を日付に変え、= や + で始まる内容を数式として扱います。テンプレートの修正はフレーズ管理で行ってください。",
            "匯出失敗：", "Export failed: ", "書き出しに失敗しました：",
            "CSV 檔案 (*.csv)|*.csv|文字檔 (*.txt)|*.txt|所有檔案 (*.*)|*.*",
            "CSV files (*.csv)|*.csv|Text files (*.txt)|*.txt|All files (*.*)|*.*",
            "CSV ファイル (*.csv)|*.csv|テキストファイル (*.txt)|*.txt|すべてのファイル (*.*)|*.*",
            "讀取失敗：", "Could not read the file: ", "読み込みに失敗しました：",
            "為避免覆蓋掉資料，這次不匯入。", "To avoid overwriting your data, nothing was imported.", "データの上書きを避けるため、今回は読み込みません。",
            "在「{0}」裡沒有讀到任何範本。", "No templates were found in \"{0}\".", "「{0}」からテンプレートが見つかりませんでした。",
            "從「{0}」讀到 {1} 筆，全部都已經在清單裡了，不需要匯入。",
            "Read {1} templates from \"{0}\"; all of them are already in your list, so there is nothing to import.",
            "「{0}」から {1} 件を読み込みましたが、すべて一覧にあるため読み込む必要はありません。",
            "從「{0}」讀到 {1} 筆：", "Read {1} templates from \"{0}\":", "「{0}」から {1} 件を読み込みました：",
            "‧新範本 {0} 筆", "• New templates: {0}", "・新しいテンプレート {0} 件",
            "‧已經存在、略過 {0} 筆", "• Already in your list, skipped: {0}", "・すでに存在するためスキップ {0} 件",
            "‧有 {0} 筆的代碼含空白、中文或超過 20 碼，無法用來叫出，已改為無代碼（內容照常匯入）",
            "• {0} codes contain spaces, CJK characters or more than 20 characters and cannot be typed; they were cleared (the content is still imported)",
            "・{0} 件のコードにスペース・全角文字が含まれるか 20 文字を超えていて使えないため、コードなしにしました（内容はそのまま読み込みます）",
            "‧代碼跟現有範本相同、但內容不同 {0} 筆（例如代碼 {1}）",
            "• Same code as an existing template but different content: {0} (e.g. code {1})",
            "・既存のテンプレートとコードが同じで内容が異なるもの {0} 件（例：コード {1}）",
            "代碼相同的要怎麼處理？", "How should templates with the same code be handled?", "コードが同じものはどうしますか？",
            "「是」＝用匯入的內容取代現有那筆\n「否」＝兩筆都保留（打這組代碼時清單會停住讓你選）\n「取消」＝這次不匯入",
            "Yes = replace the existing template with the imported one\nNo = keep both (the list will pause on that code so you can choose)\nCancel = don't import this time",
            "「はい」＝読み込んだ内容で既存のものを置き換える\n「いいえ」＝両方残す（そのコードを打つと一覧が止まり、選べます）\n「キャンセル」＝今回は読み込まない",
            "匯入範本", "Import templates", "テンプレートの読み込み",
            "確定要匯入嗎？", "Import them?", "読み込みますか？",
            "匯入完成，目前共有 {0} 筆範本。", "Import complete. You now have {0} templates.", "読み込みが完了しました。現在 {0} 件のテンプレートがあります。",

            // ── 系統匣、關於、提示 ──
            "句庫管理…", "Phrase Library…", "フレーズ管理…",
            "設定（快速鍵等）…", "Settings (hotkeys, etc.)…", "設定（ショートカットなど）…",
            "開啟程式所在資料夾", "Open program folder", "プログラムのフォルダーを開く",
            "關於…", "About…", "バージョン情報…",
            "結束", "Exit", "終了",
            "{0} 已啟動", "{0} is running", "{0} を起動しました",
            "按 {0} 叫出範本清單", "Press {0} to show the template list", "{0} でテンプレート一覧を表示",
            "；反白文字後按 {0} 快速新增", "; select text and press {0} to quick-add", "。文字を選択して {0} でクイック追加",
            "。\n點右下角的系統匣圖示可管理範本。", ".\nClick the tray icon at the bottom right to manage templates.", "。\n右下のタスクトレイのアイコンからテンプレートを管理できます。",
            "版本 {0}", "Version {0}", "バージョン {0}",
            "按快速鍵叫出常用句子清單，打代碼即可輸出到游標所在位置。",
            "Press a hotkey to show your saved phrases, then type a code to insert one at the cursor.",
            "ショートカットキーでよく使う定型文の一覧を呼び出し、コードを打つとカーソル位置に入力します。",
            "本程式以 MIT 授權開源，可自由使用、修改與散布。", "Open source under the MIT License: free to use, modify and distribute.", "MIT ライセンスのオープンソースです。自由に使用・改変・再配布できます。",
            "關於 {0}", "About {0}", "{0} について",
            "快速鍵設定有誤", "Invalid hotkey", "ショートカットキーの設定エラー",
            "請在「設定」重新指定叫出清單的快速鍵。", "Please set the list hotkey again in Settings.", "「設定」で一覧のショートカットキーを設定し直してください。",
            "快速鍵被占用", "Hotkey already in use", "ショートカットキーが使用中です",
            "{0} 已被其他程式使用，請在「設定」改用別的組合。", "{0} is already used by another program. Please choose a different combination in Settings.", "{0} は他のプログラムで使われています。「設定」で別の組み合わせにしてください。",
            "快速鍵無法啟用", "Hotkey unavailable", "ショートカットキーを有効にできません",
            "{0} 無法啟用，請在「設定」改用別的組合。", "{0} couldn't be enabled. Please choose a different combination in Settings.", "{0} を有効にできませんでした。「設定」で別の組み合わせにしてください。",
            "快速新增的快速鍵無法使用", "Quick-add hotkey unavailable", "クイック追加のショートカットキーが使えません",
            "{0} 設定有誤或已被其他程式使用，請在「設定」改用別的組合。", "{0} is invalid or used by another program. Please choose a different combination in Settings.", "{0} は設定が正しくないか、他のプログラムで使われています。「設定」で別の組み合わせにしてください。",
            "快速新增沒有執行", "Quick-add was not run", "クイック追加を実行しませんでした",
            "請先放開 Ctrl、Shift 等按鍵，再按一次 {0}。", "Release Ctrl, Shift and other keys first, then press {0} again.", "Ctrl や Shift などのキーを離してから、もう一度 {0} を押してください。",
            "已新增範本", "Template added", "テンプレートを追加しました",
            "代碼 {0}：", "Code {0}: ", "コード {0}：",
            "設定檔暫時無法寫入（可能正在同步），新設定這次有效，但沒有存檔；請稍後再到「設定」按一次確定。",
            "The settings file cannot be written right now (it may be syncing). The new settings apply for now but were not saved; please click OK in Settings again later.",
            "設定ファイルに書き込めません（同期中の可能性があります）。新しい設定は今回だけ有効で、保存されていません。しばらくしてから「設定」でもう一度 OK を押してください。",
            "{0}已經在執行了（請看右下角的系統匣圖示）。", "{0} is already running (see the tray icon at the bottom right).", "{0} はすでに実行中です（右下のタスクトレイのアイコンをご覧ください）。",

            // ── 配色主題 ──
            "經典藍", "Classic Blue", "クラシック",
            "深色", "Dark", "ダーク",
            "豆沙綠", "Soft Green", "やさしい緑",
            "暖米紙", "Sepia", "セピア",
            "護眼配色：低對比、少藍光，適合長時間閱讀。", "Eye-care colors: low contrast and less blue light, easy on the eyes for long reading.", "目にやさしい配色：コントラストとブルーライトを抑え、長時間の閲覧に向いています。",
            "森林綠", "Forest", "フォレスト",
            "摩卡棕", "Mocha", "モカ",
            "朱紅", "Vermilion", "朱色",
            "紫藤", "Wisteria", "藤色",
            "Solarized", "Solarized", "Solarized",
            "高對比", "High Contrast", "高コントラスト",
        };
    }
}
